image: openjdk:17-jdk-slim

stages:
  - build
  - test
  - report
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  ALLURE_RESULTS: "allure-results"
  PROJECT_URL: "https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/allure-report"  # Variável para a URL do relatório Allure

before_script:
  - echo "Configurando o ambiente..."
  - apt-get update && apt-get install -y maven curl unzip
  - echo "Instalando Allure versão 2.29.0..."
  - curl -L "https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip" -o allure-commandline.zip
  - unzip -q allure-commandline.zip -d /opt
  - ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
  - allure --version
  - mvn --version

build:
  stage: build
  script:
    - echo "Executando build..."
    - mvn clean install -DskipTests

test:
  stage: test
  script:
    - echo "Executando testes..."
    - mvn test
    - echo "Listando arquivos do allure-results"
    - ls -la allure-results
  artifacts:
    paths:
      - allure-results
    expire_in: 1 week

report:
  stage: report
  script:
    - echo "Gerando relatório Allure..."
    - allure generate allure-results --clean -o public/allure-report
    - echo "Listando arquivos do public/allure-report"
    - ls -la public/allure-report
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - test

pages:
  stage: deploy
  script:
    - |
      echo "Publicando relatório Allure..."
      mv public/allure-report/* public/
      echo "Listando arquivos do public para conferência"
      ls -la public
      echo "Acessar o relatório Allure em: $PROJECT_URL"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - report
  only:
    - main
  publish: public
